name: CI with SafeDep

on:
  workflow_dispatch:
    # To enable manual trigger

  push:
    branches:
      - master

jobs:
  mvn:
    strategy:
      matrix:
        profile:
          - name: 'compile-with-JDK11'
            jdk: 11
            args: '-DskipTests -Drat.skip=true -Dmaven.javadoc.skip=true clean install'
      fail-fast: false
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    # Checkout source code and run build
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.profile.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.profile.jdk }}

    # Setup environment using SafeDep pacman
    - name: Configure environment to use SafeDep Gateway
      uses: safedep/pacman@main
      with:
        gateway_url: ${{ secrets.GATEWAY_URL }}
        gateway_username: ${{ secrets.GATEWAY_USERNAME }}
        gateway_password: ${{ secrets.GATEWAY_PASSWORD }}
        package_manager: maven

    - name: Build with Maven (${{ matrix.profile.name }})
      run: mvn -B -V -e -ntp -am "-Dstyle.color=always" --projects janusgraph-all -Pjanusgraph-cache ${{ matrix.profile.args }}
      env:
        MAVEN_OPTS: -Djansi.force=true

